version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: Wallet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - wallet-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Wallet
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1111
      SPRING_LIQUIBASE_CHANGELOG: classpath:db/changelog/changelog-master.xml
    networks:
      - wallet-network

volumes:
  postgres-data:

networks:
  wallet-network:
    driver: bridge